global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    env: dev
    cluster: kubereats-postgres

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          env: dev
          cluster: kubereats-postgres
          component: prometheus
          node: local

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - 10.250.0.11:9187
        labels:
          env: dev
          cluster: kubereats-postgres
          component: postgres
          node: pg1
      - targets:
          - 10.250.0.12:9187
        labels:
          env: dev
          cluster: kubereats-postgres
          component: postgres
          node: pg2
      - targets:
          - 10.250.0.13:9187
        labels:
          env: dev
          cluster: kubereats-postgres
          component: postgres
          node: pg3

  - job_name: patroni
    metrics_path: /metrics
    static_configs:
      - targets:
          - 10.250.0.11:8008
        labels:
          env: dev
          cluster: kubereats-postgres
          component: patroni
          node: pg1
      - targets:
          - 10.250.0.12:8008
        labels:
          env: dev
          cluster: kubereats-postgres
          component: patroni
          node: pg2
      - targets:
          - 10.250.0.13:8008
        labels:
          env: dev
          cluster: kubereats-postgres
          component: patroni
          node: pg3

  - job_name: db-node-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - 10.250.0.11:9100
        labels:
          env: dev
          cluster: kubereats-postgres
          component: db-node
          node: pg1
      - targets:
          - 10.250.0.12:9100
        labels:
          env: dev
          cluster: kubereats-postgres
          component: db-node
          node: pg2
      - targets:
          - 10.250.0.13:9100
        labels:
          env: dev
          cluster: kubereats-postgres
          component: db-node
          node: pg3

  - job_name: gcs-backup-exporter
    static_configs:
      - targets:
          - gcs-backup-exporter:9817
        labels:
          env: dev
          cluster: kubereats-postgres
          component: backup
          node: gcs-backup-exporter

  - job_name: k8s-prometheus-federate-pg3
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
        - '{job=~"patroni|db-node-exporter|postgres-exporter",node="pg3"}'
    metric_relabel_configs:
      - target_label: source
        replacement: k8s-local
    static_configs:
      - targets:
          - 192.168.17.11:30990
        labels:
          env: dev
          cluster: kubereats-postgres
          component: k8s-prometheus-federation
          node: k8s-cp-01
