apiVersion: 1

datasources:
  - name: Google Cloud Monitoring
    uid: google-cloud-monitoring
    type: stackdriver
    access: proxy
    editable: true
    jsonData:
      authenticationType: gce
      defaultProject: ${GCP_PROJECT_ID}
